// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Store from "./Store.bs.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as CustomStyles from "./CustomStyles.bs.js";
import * as ReactNative from "react-native";
import * as CounterReducer from "./CounterReducer.bs.js";
import * as CounterReductive from "./CounterReductive.bs.js";
import * as NewAppScreen from "react-native/Libraries/NewAppScreen";
import * as OpenURLInBrowser from "react-native/Libraries/Core/Devtools/openURLInBrowser";

var Header = { };

var ReloadInstructions = { };

var LearnMoreLinks = { };

var DebugInstructions = { };

function App$app(Props) {
  return React.createElement(Store.AppStore.Provider.make, {
              children: null,
              store: Store.appStore
            }, React.createElement(ReactNative.StatusBar, {
                  barStyle: "dark-content"
                }), React.createElement(ReactNative.SafeAreaView, {
                  children: React.createElement(ReactNative.ScrollView, {
                        contentInsetAdjustmentBehavior: "automatic",
                        style: CustomStyles.styles.scrollView,
                        children: null
                      }, Belt_Option.isNone(global.hermesInternal) ? null : React.createElement(ReactNative.View, {
                              style: CustomStyles.styles.engine,
                              children: React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.footer,
                                    children: "Engine: Hermes"
                                  })
                            }), React.createElement(NewAppScreen.Header, { }), React.createElement(ReactNative.View, {
                            style: CustomStyles.styles.body,
                            children: null
                          }, React.createElement(CounterReducer.make, { }), React.createElement(CounterReductive.make, { }), React.createElement(ReactNative.View, {
                                style: CustomStyles.styles.sectionContainer,
                                children: null
                              }, React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionTitle,
                                    children: "See Your Changes"
                                  }), React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionDescription,
                                    children: React.createElement(NewAppScreen.ReloadInstructions, { })
                                  })), React.createElement(ReactNative.View, {
                                style: CustomStyles.styles.sectionContainer,
                                children: null
                              }, React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionTitle,
                                    children: "Debug"
                                  }), React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionDescription,
                                    children: React.createElement(NewAppScreen.DebugInstructions, { })
                                  })), React.createElement(ReactNative.View, {
                                style: CustomStyles.styles.sectionContainer,
                                children: null
                              }, React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionTitle,
                                    children: "Learn More"
                                  }), React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionDescription,
                                    children: "Read the docs to discover what to do next:"
                                  })), React.createElement(ReactNative.View, {
                                style: CustomStyles.styles.sectionContainer,
                                children: null
                              }, React.createElement(ReactNative.Text, {
                                    style: CustomStyles.styles.sectionDescription,
                                    children: React.createElement(ReactNative.Text, {
                                          style: CustomStyles.styles.highlight,
                                          children: "Reason React Native"
                                        })
                                  }), React.createElement(ReactNative.TouchableOpacity, {
                                    onPress: (function (param) {
                                        OpenURLInBrowser.default("https://reasonml-community.github.io/reason-react-native/en/docs/");
                                        return /* () */0;
                                      }),
                                    children: React.createElement(ReactNative.Text, {
                                          style: {
                                            color: NewAppScreen.Colors.primary,
                                            fontSize: 18,
                                            fontWeight: "400",
                                            marginTop: 8
                                          },
                                          children: "https://reasonml-community.github.io/\nreason-react-native/"
                                        })
                                  })), React.createElement(ReactNative.View, {
                                style: CustomStyles.styles.sectionContainer,
                                children: React.createElement(ReactNative.Text, {
                                      style: CustomStyles.styles.sectionDescription,
                                      children: React.createElement(ReactNative.Text, {
                                            style: CustomStyles.styles.highlight,
                                            children: "React Native"
                                          })
                                    })
                              }), React.createElement(NewAppScreen.LearnMoreLinks, { })))
                }));
}

var app = App$app;

export {
  Header ,
  ReloadInstructions ,
  LearnMoreLinks ,
  DebugInstructions ,
  app ,
  
}
/* Store Not a pure module */
