// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Store from "./Store.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";

function selector(state) {
  return state.counter;
}

function CounterReductive(Props) {
  var counter = Curry._1(Store.AppStore.useSelector, selector);
  var dispatch = Curry._1(Store.AppStore.useDispatch, /* () */0);
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNative.Text, {
                  children: String(counter)
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (_evt) {
                      return Curry._1(dispatch, /* Increment */0);
                    }),
                  title: "Inc"
                }), React.createElement(ReactNative.Button, {
                  onPress: (function (_evt) {
                      return Curry._1(dispatch, /* Decrement */1);
                    }),
                  title: "Dec"
                }));
}

var make = CounterReductive;

export {
  selector ,
  make ,
  
}
/* Store Not a pure module */
