// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Reductive from "reductive/src/reductive.js";
import * as ReductiveContext from "reductive/src/reductiveContext.js";

function appReducer(param, action) {
  var counter = param.counter;
  if (action) {
    return {
            counter: counter - 1 | 0
          };
  } else {
    return {
            counter: counter + 1 | 0
          };
  }
}

var appStore = Reductive.Store.create(appReducer, {
      counter: 0
    }, undefined, /* () */0);

var include = ReductiveContext.Make({ });

var AppStore = include;

export {
  appReducer ,
  appStore ,
  AppStore ,
  
}
/* appStore Not a pure module */
